import type { DitherOptions } from "@/lib/dither";
import type { AssembleParams } from "@/lib/assembleField";
import type { ParticleParams } from "@/lib/particleField";

/**
 * Code generation for the studio.
 *
 * What comes out has to survive leaving this repo, so it carries no imports
 * from here, no Motion, and no Tailwind — just React (or nothing at all, for
 * the HTML build) and a canvas. The image travels with it as a data URI, and
 * the develop lag is a hand-rolled lerp rather than a spring, so there is
 * nothing to install.
 */

export type ExportSettings = DitherOptions &
  ParticleParams &
  AssembleParams & {
    ink: string;
    ground: string;
    round: boolean;
    /** Scroll the develop takes, as a multiple of the viewport height. */
    runway: number;
    /** Develop lag per frame: 0 snaps to the scrollbar, 1 never catches up. */
    lag: number;
  };

const BAYER_SRC = `[
  [0, 32, 8, 40, 2, 34, 10, 42],
  [48, 16, 56, 24, 50, 18, 58, 26],
  [12, 44, 4, 36, 14, 46, 6, 38],
  [60, 28, 52, 20, 62, 30, 54, 22],
  [3, 35, 11, 43, 1, 33, 9, 41],
  [51, 19, 59, 27, 49, 17, 57, 25],
  [15, 47, 7, 39, 13, 45, 5, 37],
  [63, 31, 55, 23, 61, 29, 53, 21],
]`;

function constants(s: ExportSettings) {
  return `const GRID_W = ${s.gridW};
const INK = ${JSON.stringify(s.ink)};
const GROUND = ${JSON.stringify(s.ground)};
const ROUND = ${s.round};
const INVERT = ${s.invert};

/* Tone: how luminance becomes ink density. */
const WEIGHT = ${s.weight};
const GAMMA = ${s.gamma};
const BG_CUT = ${s.bgCut};
const FIG_HI = ${s.figHi};
/* Fraction of the height over which the print dissolves at its bottom edge. */
const FADE = ${s.fade};

/* Develop: per-cell thresholds, and how wide each cell's fade-in is. */
const SPREAD = ${s.spread};
const CELL_FADE = 0.06;
/* Scroll the develop takes, as a multiple of the viewport height. */
const RUNWAY = ${s.runway};
/* Develop lag per frame: 0 snaps to the scrollbar, 1 never catches up. */
const EASE = ${s.lag};

/* Colour: each cell keeps the colour of the pixel it came from, instead of
   everything being drawn in one ink. Cells are sorted by palette entry so
   painting sets fillStyle once per colour, not once per cell. */
const COLOUR = ${s.colour};
const LEVELS = 8;

const BAYER = ${BAYER_SRC};`;
}

/** A self-contained React client component. No dependencies beyond React. */
export function toReact(image: string, s: ExportSettings) {
  return `"use client";

/**
 * Scroll-developed dither — generated by Darwin.
 *
 * The image is sampled to a ${s.gridW}-column grid and thresholded through an 8x8
 * Bayer matrix, so tone is carried by how many cells survive in a neighbourhood
 * rather than by any grey. Each surviving cell gets its own threshold, and
 * scroll progress sweeps past them, so the picture comes up in grain like a
 * darkroom print instead of wiping or fading in.
 *
 * Drop it anywhere. The section is ${s.runway} viewports tall and pins its own stage,
 * so it needs no wrapper and no scroll library.
 */

import { useEffect, useRef } from "react";

const IMAGE =
  ${JSON.stringify(image)};

${constants(s)}

type Cells = {
  x: Int16Array; y: Int16Array; t: Float32Array;
  n: number; cols: number; rows: number;
  tone?: Uint16Array; palette?: string[];
};

const clamp = (v: number, a = 0, b = 1) => Math.max(a, Math.min(b, v));

const smoothstep = (t: number) => {
  const c = clamp(t);
  return c * c * (3 - 2 * c);
};

/* Deterministic, so the picture always develops in the same order. */
function hash(x: number, y: number) {
  const h = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
  return h - Math.floor(h);
}

function buildCells(image: HTMLImageElement): Cells {
  const cols = GRID_W;
  const rows = Math.max(1, Math.round((cols * image.naturalHeight) / image.naturalWidth));

  const grid = document.createElement("canvas");
  grid.width = cols;
  grid.height = rows;
  const gctx = grid.getContext("2d", { willReadFrequently: true })!;
  gctx.imageSmoothingEnabled = true;
  gctx.drawImage(image, 0, 0, cols, rows);
  const data = gctx.getImageData(0, 0, cols, rows).data;

  const xs: number[] = [];
  const ys: number[] = [];
  const tones: number[] = [];
  /* Packed quantised RGB -> palette index. */
  const index = new Map<number, number>();
  const palette: string[] = [];
  const step = 255 / (LEVELS - 1);
  const ts: number[] = [];
  const span = Math.max(1, rows * FADE);

  for (let y = 0; y < rows; y++) {
    const bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const alpha = data[i + 3] / 255;
      const threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

      if (COLOUR) {
        /* Every cell survives; only the bottom fade thins them, and it does so
           through the same Bayer matrix so the edge dissolves rather than cuts. */
        if (alpha < 0.5 || bottom < threshold) continue;
        const qr = Math.round(Math.round(data[i] / step) * step);
        const qg = Math.round(Math.round(data[i + 1] / step) * step);
        const qb = Math.round(Math.round(data[i + 2] / step) * step);
        const packed = (qr << 16) | (qg << 8) | qb;
        let tone = index.get(packed);
        if (tone === undefined) {
          tone = palette.length;
          index.set(packed, tone);
          palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
        }
        xs.push(x);
        ys.push(y);
        tones.push(tone);
        ts.push(clamp(hash(x, y) * SPREAD));
        continue;
      }

      let l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      l = l * alpha + 255 * (1 - alpha);
      if (INVERT) l = 255 - l;
      if (l < BG_CUT) continue;

      const value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
      if ((1 - value) * WEIGHT * bottom > threshold) {
        tones.push(0);
        xs.push(x);
        ys.push(y);
        ts.push(clamp(hash(x, y) * SPREAD));
      }
    }
  }

  /* Sort by palette entry so painting sets fillStyle once per colour instead
     of once per cell. Squares do not overlap at rest, so reordering is
     invisible. */
  if (COLOUR) {
    const order = xs.map((_, i) => i).sort((a, b) => tones[a] - tones[b]);
    const ox = order.map((i) => xs[i]);
    const oy = order.map((i) => ys[i]);
    const ot = order.map((i) => tones[i]);
    const od = order.map((i) => ts[i]);
    for (let k = 0; k < order.length; k++) {
      xs[k] = ox[k];
      ys[k] = oy[k];
      tones[k] = ot[k];
      ts[k] = od[k];
    }
  }

  return {
    x: Int16Array.from(xs),
    y: Int16Array.from(ys),
    t: Float32Array.from(ts),
    n: xs.length,
    cols,
    rows,
    tone: COLOUR ? Uint16Array.from(tones) : undefined,
    palette: COLOUR ? palette : undefined,
  };
}

export default function ScrollDither() {
  const sectionRef = useRef<HTMLElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const section = sectionRef.current;
    const canvas = canvasRef.current;
    if (!section || !canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let cells: Cells | null = null;
    let cell = 1;
    let current = 0;
    let frame = 0;
    /* Reduced motion keeps the scroll — that is the user's own gesture — and
       drops only the lag, so nothing keeps moving after they stop. */
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    function layout() {
      if (!cells || !ctx || !canvas || !section) return;
      const box = section.getBoundingClientRect();
      const stage = Math.min(window.innerHeight, box.height);
      cell = Math.min((box.width * 0.8) / cells.cols, (stage * 0.88) / cells.rows);

      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.style.width = cells.cols * cell + "px";
      canvas.style.height = cells.rows * cell + "px";
      canvas.width = Math.round(cells.cols * cell * dpr);
      canvas.height = Math.round(cells.rows * cell * dpr);
      /* Assigning width/height clears the transform, so set it after. */
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      paint(current);
    }

    function progress() {
      if (!section) return 0;
      const r = section.getBoundingClientRect();
      const total = section.offsetHeight - window.innerHeight;
      return total > 0 ? clamp(-r.top / total) : 0;
    }

    function paint(p: number) {
      if (!cells || !ctx) return;
      ctx.clearRect(0, 0, cells.cols * cell, cells.rows * cell);
      const tone = cells.tone;
      const palette = cells.palette;
      /* Cells are sorted by palette entry, so this only changes on a boundary. */
      let last = -1;
      if (!tone || !palette) ctx.fillStyle = INK;
      const r = cell / 2;
      const settled = p > 0.999;

      for (let i = 0; i < cells.n; i++) {
        if (tone && palette && tone[i] !== last) {
          last = tone[i];
          ctx.fillStyle = palette[last];
        }
        if (!settled) {
          const a = (p - cells.t[i]) / CELL_FADE;
          if (a <= 0) continue;
          ctx.globalAlpha = a < 1 ? a : 1;
        }
        const px = cells.x[i] * cell;
        const py = cells.y[i] * cell;
        if (ROUND) {
          ctx.beginPath();
          ctx.arc(px + r, py + r, r, 0, 6.2832);
          ctx.fill();
        } else {
          ctx.fillRect(px, py, cell, cell);
        }
      }
      ctx.globalAlpha = 1;
    }

    function loop() {
      const target = progress();
      current = reduce ? target : current + (target - current) * EASE;
      paint(current);
      frame = requestAnimationFrame(loop);
    }

    /* Only run while the section is on screen. */
    const io = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          if (!frame) frame = requestAnimationFrame(loop);
        } else if (frame) {
          cancelAnimationFrame(frame);
          frame = 0;
        }
      },
      { rootMargin: "200px" }
    );

    const ro = new ResizeObserver(layout);
    const img = new Image();
    img.onload = () => {
      cells = buildCells(img);
      layout();
      ro.observe(section);
      io.observe(section);
    };
    img.src = IMAGE;

    return () => {
      if (frame) cancelAnimationFrame(frame);
      ro.disconnect();
      io.disconnect();
    };
  }, []);

  return (
    <section
      ref={sectionRef}
      style={{ position: "relative", height: \`\${RUNWAY * 100}vh\`, background: GROUND }}
    >
      <div
        style={{
          position: "sticky",
          top: 0,
          height: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        <canvas ref={canvasRef} aria-hidden style={{ display: "block" }} />
      </div>
    </section>
  );
}
`;
}

/** A single self-contained block for a page that is not running React. */
export function toHtml(image: string, s: ExportSettings) {
  return `<!-- Scroll-developed dither — generated by Darwin.
     Paste anywhere in your page. No dependencies, no build step. -->
<section class="sd-scene">
  <div class="sd-stage"><canvas class="sd-canvas" aria-hidden="true"></canvas></div>
</section>

<style>
  .sd-scene { position: relative; height: ${s.runway * 100}vh; background: ${s.ground}; }
  .sd-stage { position: sticky; top: 0; height: 100vh; display: flex;
              align-items: center; justify-content: center; overflow: hidden; }
  .sd-canvas { display: block; }
</style>

<script>
(function () {
  var IMAGE =
    ${JSON.stringify(image)};

  ${constants(s).split("\n").join("\n  ")}

  var scene = document.currentScript.parentNode.querySelector(".sd-scene")
           || document.querySelector(".sd-scene");
  var canvas = scene.querySelector(".sd-canvas");
  var ctx = canvas.getContext("2d");

  var cells = null, cell = 1, current = 0, frame = 0;
  /* Reduced motion keeps the scroll — that is the user's own gesture — and
     drops only the lag, so nothing keeps moving after they stop. */
  var reduce = matchMedia("(prefers-reduced-motion: reduce)").matches;

  function clamp(v, a, b) {
    a = a === undefined ? 0 : a; b = b === undefined ? 1 : b;
    return Math.max(a, Math.min(b, v));
  }
  function smoothstep(t) { var c = clamp(t); return c * c * (3 - 2 * c); }
  function hash(x, y) {
    var h = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
    return h - Math.floor(h);
  }

  function buildCells(image) {
    var cols = GRID_W;
    var rows = Math.max(1, Math.round(cols * image.naturalHeight / image.naturalWidth));

    var grid = document.createElement("canvas");
    grid.width = cols; grid.height = rows;
    var g = grid.getContext("2d", { willReadFrequently: true });
    g.imageSmoothingEnabled = true;
    g.drawImage(image, 0, 0, cols, rows);
    var data = g.getImageData(0, 0, cols, rows).data;

    var xs = [], ys = [], ts = [];
    var tones = [];
    /* Packed quantised RGB -> palette index. */
    var index = {}, palette = [], step = 255 / (LEVELS - 1);
    var span = Math.max(1, rows * FADE);

    for (var y = 0; y < rows; y++) {
      var bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
      for (var x = 0; x < cols; x++) {
        var i = (y * cols + x) * 4;
        var alpha = data[i + 3] / 255;
        var threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

        if (COLOUR) {
          /* Every cell survives; only the bottom fade thins them, through the
             same Bayer matrix so the edge dissolves rather than cuts. */
          if (alpha < 0.5 || bottom < threshold) continue;
          var qr = Math.round(Math.round(data[i] / step) * step);
          var qg = Math.round(Math.round(data[i + 1] / step) * step);
          var qb = Math.round(Math.round(data[i + 2] / step) * step);
          var packed = (qr << 16) | (qg << 8) | qb;
          var tone = index[packed];
          if (tone === undefined) {
            tone = palette.length;
            index[packed] = tone;
            palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
          }
          xs.push(x); ys.push(y); tones.push(tone);
          ts.push(clamp(hash(x, y) * SPREAD));
          continue;
        }

        var l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
        l = l * alpha + 255 * (1 - alpha);
        if (INVERT) l = 255 - l;
        if (l < BG_CUT) continue;

        var value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
        if ((1 - value) * WEIGHT * bottom > threshold) {
          tones.push(0);
          xs.push(x); ys.push(y); ts.push(clamp(hash(x, y) * SPREAD));
        }
      }
    }

    /* Sort by palette entry so painting sets fillStyle once per colour instead
       of once per cell. Squares do not overlap at rest, so reordering is
       invisible. */
    if (COLOUR) {
      var order = xs.map(function (_, i) { return i; })
                    .sort(function (a, b) { return tones[a] - tones[b]; });
      var ox = order.map(function (i) { return xs[i]; });
      var oy = order.map(function (i) { return ys[i]; });
      var ot = order.map(function (i) { return tones[i]; });
      var od = order.map(function (i) { return ts[i]; });
      for (var q = 0; q < order.length; q++) {
        xs[q] = ox[q]; ys[q] = oy[q]; tones[q] = ot[q];
        ts[q] = od[q];
      }
    }

    return {
      x: Int16Array.from(xs), y: Int16Array.from(ys), t: Float32Array.from(ts),
      n: xs.length, cols: cols, rows: rows,
      tone: COLOUR ? Uint16Array.from(tones) : undefined,
      palette: COLOUR ? palette : undefined
    };
  }

  function layout() {
    if (!cells) return;
    var box = scene.getBoundingClientRect();
    var stage = Math.min(innerHeight, box.height);
    cell = Math.min(box.width * 0.8 / cells.cols, stage * 0.88 / cells.rows);

    var dpr = Math.min(devicePixelRatio || 1, 2);
    canvas.style.width = cells.cols * cell + "px";
    canvas.style.height = cells.rows * cell + "px";
    canvas.width = Math.round(cells.cols * cell * dpr);
    canvas.height = Math.round(cells.rows * cell * dpr);
    /* Assigning width/height clears the transform, so set it after. */
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    paint(current);
  }

  function progress() {
    var r = scene.getBoundingClientRect();
    var total = scene.offsetHeight - innerHeight;
    return total > 0 ? clamp(-r.top / total) : 0;
  }

  function paint(p) {
    if (!cells) return;
    ctx.clearRect(0, 0, cells.cols * cell, cells.rows * cell);
    var tone = cells.tone, palette = cells.palette;
    /* Cells are sorted by palette entry, so this only changes on a boundary. */
    var last = -1;
    if (!tone || !palette) ctx.fillStyle = INK;
    var r = cell / 2, settled = p > 0.999, i, a, px, py;

    for (i = 0; i < cells.n; i++) {
      if (tone && palette && tone[i] !== last) {
        last = tone[i]; ctx.fillStyle = palette[last];
      }
      if (!settled) {
        a = (p - cells.t[i]) / CELL_FADE;
        if (a <= 0) continue;
        ctx.globalAlpha = a < 1 ? a : 1;
      }
      px = cells.x[i] * cell; py = cells.y[i] * cell;
      if (ROUND) { ctx.beginPath(); ctx.arc(px + r, py + r, r, 0, 6.2832); ctx.fill(); }
      else ctx.fillRect(px, py, cell, cell);
    }
    ctx.globalAlpha = 1;
  }

  function loop() {
    var target = progress();
    current = reduce ? target : current + (target - current) * EASE;
    paint(current);
    frame = requestAnimationFrame(loop);
  }

  var img = new Image();
  img.onload = function () {
    cells = buildCells(img);
    layout();
    addEventListener("resize", layout);
    /* Only run while the section is on screen. */
    new IntersectionObserver(function (entries) {
      if (entries[0].isIntersecting) { if (!frame) frame = requestAnimationFrame(loop); }
      else if (frame) { cancelAnimationFrame(frame); frame = 0; }
    }, { rootMargin: "200px" }).observe(scene);
  };
  img.src = IMAGE;
})();
</script>
`;
}

/** Constants shared by the two scatter templates. */
function scatterConstants(s: ExportSettings) {
  return `const GRID_W = ${s.gridW};
const INK = ${JSON.stringify(s.ink)};
const GROUND = ${JSON.stringify(s.ground)};
const INVERT = ${s.invert};

/* Tone: which cells survive the dither and become particles. */
const WEIGHT = ${s.weight};
const GAMMA = ${s.gamma};
const BG_CUT = ${s.bgCut};
const FIG_HI = ${s.figHi};
const FADE = ${s.fade};

/* The cursor's effect, all as fractions of the field's own width. */
const REACH = ${s.reach};
const PUSH = ${s.push};
const DRIFT = ${s.drift};
const LIFT = ${s.lift};
/* Per-frame easing toward the target. Low is floaty. */
const EASE = ${s.ease};
/* Particles thin as they disperse; squares leave this much of their cell. */
const THIN = ${s.thin};
const FILL = ${s.fill};

/* Colour: each cell keeps the colour of the pixel it came from, instead of
   everything being drawn in one ink. Cells are sorted by palette entry so
   painting sets fillStyle once per colour, not once per cell. */
const COLOUR = ${s.colour};
const LEVELS = 8;

const BAYER = ${BAYER_SRC};`;
}

/** A self-contained React client component. No dependencies beyond React. */
export function toReactScatter(image: string, s: ExportSettings) {
  return `"use client";

/**
 * Cursor-scatter pixel field — generated by Darwin.
 *
 * The image is sampled to a ${s.gridW}-column grid and thresholded through an 8x8
 * Bayer matrix; every surviving cell becomes a particle that remembers where it
 * belongs. The cursor pushes the ones near it radially out, stirs them with a
 * turbulence keyed off each particle's own phase, and lifts them, because air
 * rises. Each particle eases toward that target rather than being set to it,
 * which is what makes the field read as smoke instead of a shockwave.
 *
 * Nothing moves until you point at it, and the loop stops asking for frames
 * once the field settles.
 */

import { useEffect, useRef } from "react";

const IMAGE =
  ${JSON.stringify(image)};

${scatterConstants(s)}

const clamp = (v: number, a = 0, b = 1) => Math.max(a, Math.min(b, v));

const smoothstep = (t: number) => {
  const c = clamp(t);
  return c * c * (3 - 2 * c);
};

type Field = {
  gx: Int16Array; gy: Int16Array;
  dx: Float32Array; dy: Float32Array;
  seed: Float32Array;
  n: number; cols: number; rows: number;
  tone?: Uint16Array; palette?: string[];
};

/* Dither the image down to the cells that will become particles. */
function buildField(image: HTMLImageElement): Field {
  const cols = GRID_W;
  const rows = Math.max(1, Math.round((cols * image.naturalHeight) / image.naturalWidth));

  const grid = document.createElement("canvas");
  grid.width = cols;
  grid.height = rows;
  const g = grid.getContext("2d", { willReadFrequently: true })!;
  g.imageSmoothingEnabled = true;
  g.drawImage(image, 0, 0, cols, rows);
  const data = g.getImageData(0, 0, cols, rows).data;

  const xs: number[] = [];
  const ys: number[] = [];
  const tones: number[] = [];
  /* Packed quantised RGB -> palette index. */
  const index = new Map<number, number>();
  const palette: string[] = [];
  const step = 255 / (LEVELS - 1);
  const span = Math.max(1, rows * FADE);

  for (let y = 0; y < rows; y++) {
    const bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const alpha = data[i + 3] / 255;
      const threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

      if (COLOUR) {
        /* Every cell survives; only the bottom fade thins them, and it does so
           through the same Bayer matrix so the edge dissolves rather than cuts. */
        if (alpha < 0.5 || bottom < threshold) continue;
        const qr = Math.round(Math.round(data[i] / step) * step);
        const qg = Math.round(Math.round(data[i + 1] / step) * step);
        const qb = Math.round(Math.round(data[i + 2] / step) * step);
        const packed = (qr << 16) | (qg << 8) | qb;
        let tone = index.get(packed);
        if (tone === undefined) {
          tone = palette.length;
          index.set(packed, tone);
          palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
        }
        xs.push(x);
        ys.push(y);
        tones.push(tone);
        continue;
      }

      let l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      l = l * alpha + 255 * (1 - alpha);
      if (INVERT) l = 255 - l;
      if (l < BG_CUT) continue;

      const value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
      if ((1 - value) * WEIGHT * bottom > threshold) {
        tones.push(0);
        xs.push(x);
        ys.push(y);
      }
    }
  }

  /* Sort by palette entry so painting sets fillStyle once per colour instead
     of once per cell. Squares do not overlap at rest, so reordering is
     invisible. */
  if (COLOUR) {
    const order = xs.map((_, i) => i).sort((a, b) => tones[a] - tones[b]);
    const ox = order.map((i) => xs[i]);
    const oy = order.map((i) => ys[i]);
    const ot = order.map((i) => tones[i]);
    for (let k = 0; k < order.length; k++) {
      xs[k] = ox[k];
      ys[k] = oy[k];
      tones[k] = ot[k];
    }
  }

  const n = xs.length;
  const seed = new Float32Array(n);
  for (let i = 0; i < n; i++) seed[i] = Math.random();

  return {
    gx: Int16Array.from(xs), gy: Int16Array.from(ys),
    dx: new Float32Array(n), dy: new Float32Array(n),
    seed, n, cols, rows,
    tone: COLOUR ? Uint16Array.from(tones) : undefined,
    palette: COLOUR ? palette : undefined,
  };
}

export default function PixelScatter() {
  const hostRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const host = hostRef.current;
    const canvas = canvasRef.current;
    if (!host || !canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let field: Field | null = null;
    let W = 0, H = 0, cell = 1, originX = 0, originY = 0;
    let frame = 0;
    /* Set while the field is at rest and the cursor is away. */
    let idle = false;
    let targetX = -9999, targetY = -9999, curX = -9999, curY = -9999;

    /* Reduced motion keeps the cursor push — that is the user's own gesture —
       and drops only the turbulence, which oscillates on its own. */
    const calm = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const start = performance.now();

    function layout() {
      if (!field || !host || !canvas || !ctx) return;
      const box = host.getBoundingClientRect();
      if (!box.width || !box.height) return;
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      W = Math.round(box.width * dpr);
      H = Math.round(box.height * dpr);
      canvas.width = W;
      canvas.height = H;
      canvas.style.width = box.width + "px";
      canvas.style.height = box.height + "px";
      /* Leave margin on every side for particles to disperse into. */
      cell = Math.min((W * 0.72) / field.cols, (H * 0.72) / field.rows);
      originX = (W - field.cols * cell) / 2;
      originY = (H - field.rows * cell) / 2;
      idle = false;
    }

    function step(time: number) {
      if (!field || !ctx) return false;
      const span = field.cols * cell;
      const reach = span * REACH;
      const reach2 = reach * reach;
      const base = cell * FILL;
      const pushK = span * PUSH, driftK = span * DRIFT, liftK = span * LIFT;
      const half = cell * 0.5;

      ctx.clearRect(0, 0, W, H);
      const tone = field.tone;
      const palette = field.palette;
      /* Cells are sorted by palette entry, so this only changes on a boundary. */
      let last = -1;
      if (!tone || !palette) ctx.fillStyle = INK;
      let moving = false;

      for (let i = 0; i < field.n; i++) {
        if (tone && palette && tone[i] !== last) {
          last = tone[i];
          ctx.fillStyle = palette[last];
        }

        const homeX = originX + field.gx[i] * cell + half;
        const homeY = originY + field.gy[i] * cell + half;
        const vx = homeX - curX, vy = homeY - curY;
        const d2 = vx * vx + vy * vy;

        let tx = 0, ty = 0, ev = 0;
        /* Only particles inside the reach do any trig. */
        if (d2 < reach2) {
          const d = Math.sqrt(d2) || 0.0001;
          const env = 1 - d / reach;
          ev = env * env;
          const phase = field.seed[i] * 6.283;
          const turb = calm ? 0 : ev * driftK;
          tx = (vx / d) * ev * pushK
             + turb * Math.sin(time * 0.9 + (field.gx[i] / field.cols) * 28 + phase)
             + turb * 0.5 * Math.sin(time * 1.9 + phase * 1.7);
          ty = (vy / d) * ev * pushK
             + turb * Math.cos(time * 0.8 + (field.gy[i] / field.rows) * 6.4 + phase)
             + turb * 0.5 * Math.cos(time * 1.7 + phase * 1.3)
             - ev * liftK;
        }

        const dx = field.dx[i] + (tx - field.dx[i]) * EASE;
        const dy = field.dy[i] + (ty - field.dy[i]) * EASE;
        field.dx[i] = dx;
        field.dy[i] = dy;
        if (!moving && dx * dx + dy * dy > 0.02) moving = true;

        const s = base * (1 - ev * THIN);
        ctx.fillRect(homeX + dx - s * 0.5, homeY + dy - s * 0.5, s, s);
      }
      return moving;
    }

    function loop() {
      frame = requestAnimationFrame(loop);
      if (idle || !W) return;
      if (curX < -9000) { curX = targetX; curY = targetY; }
      else { curX += (targetX - curX) * 0.1; curY += (targetY - curY) * 0.1; }
      const moving = step((performance.now() - start) / 1000);
      idle = !moving && targetX < -9000;
    }

    function onMove(e: PointerEvent) {
      const box = canvas!.getBoundingClientRect();
      if (!box.width) return;
      targetX = (e.clientX - box.left) * (W / box.width);
      targetY = (e.clientY - box.top) * (H / box.height);
      idle = false;
    }
    function onLeave() {
      targetX = -9999;
      targetY = -9999;
      idle = false;
    }

    const ro = new ResizeObserver(layout);
    const img = new Image();
    img.onload = () => {
      field = buildField(img);
      layout();
      ro.observe(host);
      frame = requestAnimationFrame(loop);
    };
    img.src = IMAGE;

    host.addEventListener("pointermove", onMove);
    host.addEventListener("pointerleave", onLeave);

    return () => {
      if (frame) cancelAnimationFrame(frame);
      ro.disconnect();
      host.removeEventListener("pointermove", onMove);
      host.removeEventListener("pointerleave", onLeave);
    };
  }, []);

  return (
    <div
      ref={hostRef}
      style={{ position: "relative", width: "100%", height: "70vh", background: GROUND }}
    >
      <canvas ref={canvasRef} aria-hidden style={{ display: "block" }} />
    </div>
  );
}
`;
}

/** A single self-contained block for a page that is not running React. */
export function toHtmlScatter(image: string, s: ExportSettings) {
  return `<!-- Cursor-scatter pixel field — generated by Darwin.
     Paste anywhere in your page. No dependencies, no build step. -->
<div class="ps-host"><canvas class="ps-canvas" aria-hidden="true"></canvas></div>

<style>
  .ps-host { position: relative; width: 100%; height: 70vh; background: ${s.ground}; }
  .ps-canvas { display: block; }
</style>

<script>
(function () {
  var IMAGE =
    ${JSON.stringify(image)};

  ${scatterConstants(s).split("\n").join("\n  ")}

  var host = document.currentScript.parentNode.querySelector(".ps-host")
          || document.querySelector(".ps-host");
  var canvas = host.querySelector(".ps-canvas");
  var ctx = canvas.getContext("2d");

  var field = null, W = 0, H = 0, cell = 1, originX = 0, originY = 0, frame = 0;
  /* Set while the field is at rest and the cursor is away. */
  var idle = false;
  var targetX = -9999, targetY = -9999, curX = -9999, curY = -9999;
  /* Reduced motion keeps the cursor push and drops only the turbulence. */
  var calm = matchMedia("(prefers-reduced-motion: reduce)").matches;
  var start = performance.now();

  function clamp(v, a, b) {
    a = a === undefined ? 0 : a; b = b === undefined ? 1 : b;
    return Math.max(a, Math.min(b, v));
  }
  function smoothstep(t) { var c = clamp(t); return c * c * (3 - 2 * c); }

  function buildField(image) {
    var cols = GRID_W;
    var rows = Math.max(1, Math.round(cols * image.naturalHeight / image.naturalWidth));

    var grid = document.createElement("canvas");
    grid.width = cols; grid.height = rows;
    var g = grid.getContext("2d", { willReadFrequently: true });
    g.imageSmoothingEnabled = true;
    g.drawImage(image, 0, 0, cols, rows);
    var data = g.getImageData(0, 0, cols, rows).data;

    var xs = [], ys = [];
    var tones = [];
    /* Packed quantised RGB -> palette index. */
    var index = {}, palette = [], step = 255 / (LEVELS - 1);
    var span = Math.max(1, rows * FADE);
    for (var y = 0; y < rows; y++) {
      var bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
      for (var x = 0; x < cols; x++) {
        var i = (y * cols + x) * 4;
        var alpha = data[i + 3] / 255;
        var threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

        if (COLOUR) {
          /* Every cell survives; only the bottom fade thins them, through the
             same Bayer matrix so the edge dissolves rather than cuts. */
          if (alpha < 0.5 || bottom < threshold) continue;
          var qr = Math.round(Math.round(data[i] / step) * step);
          var qg = Math.round(Math.round(data[i + 1] / step) * step);
          var qb = Math.round(Math.round(data[i + 2] / step) * step);
          var packed = (qr << 16) | (qg << 8) | qb;
          var tone = index[packed];
          if (tone === undefined) {
            tone = palette.length;
            index[packed] = tone;
            palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
          }
          xs.push(x); ys.push(y); tones.push(tone);
          continue;
        }

        var l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
        l = l * alpha + 255 * (1 - alpha);
        if (INVERT) l = 255 - l;
        if (l < BG_CUT) continue;
        var value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
        if ((1 - value) * WEIGHT * bottom > threshold) {
          tones.push(0);
          xs.push(x); ys.push(y);
        }
      }
    }

    /* Sort by palette entry so painting sets fillStyle once per colour instead
       of once per cell. Squares do not overlap at rest, so reordering is
       invisible. */
    if (COLOUR) {
      var order = xs.map(function (_, i) { return i; })
                    .sort(function (a, b) { return tones[a] - tones[b]; });
      var ox = order.map(function (i) { return xs[i]; });
      var oy = order.map(function (i) { return ys[i]; });
      var ot = order.map(function (i) { return tones[i]; });
      for (var q = 0; q < order.length; q++) {
        xs[q] = ox[q]; ys[q] = oy[q]; tones[q] = ot[q];
      }
    }

    var n = xs.length, seed = new Float32Array(n);
    for (var k = 0; k < n; k++) seed[k] = Math.random();
    return {
      gx: Int16Array.from(xs), gy: Int16Array.from(ys),
      dx: new Float32Array(n), dy: new Float32Array(n),
      seed: seed, n: n, cols: cols, rows: rows,
      tone: COLOUR ? Uint16Array.from(tones) : undefined,
      palette: COLOUR ? palette : undefined
    };
  }

  function layout() {
    if (!field) return;
    var box = host.getBoundingClientRect();
    if (!box.width || !box.height) return;
    var dpr = Math.min(devicePixelRatio || 1, 2);
    W = Math.round(box.width * dpr); H = Math.round(box.height * dpr);
    canvas.width = W; canvas.height = H;
    canvas.style.width = box.width + "px";
    canvas.style.height = box.height + "px";
    /* Leave margin on every side for particles to disperse into. */
    cell = Math.min(W * 0.72 / field.cols, H * 0.72 / field.rows);
    originX = (W - field.cols * cell) / 2;
    originY = (H - field.rows * cell) / 2;
    idle = false;
  }

  function step(time) {
    var span = field.cols * cell;
    var reach = span * REACH, reach2 = reach * reach;
    var base = cell * FILL;
    var pushK = span * PUSH, driftK = span * DRIFT, liftK = span * LIFT;
    var half = cell * 0.5, moving = false, i;

    ctx.clearRect(0, 0, W, H);
    var tone = field.tone, palette = field.palette;
    /* Cells are sorted by palette entry, so this only changes on a boundary. */
    var last = -1;
    if (!tone || !palette) ctx.fillStyle = INK;

    for (i = 0; i < field.n; i++) {
      if (tone && palette && tone[i] !== last) {
        last = tone[i]; ctx.fillStyle = palette[last];
      }

      var homeX = originX + field.gx[i] * cell + half;
      var homeY = originY + field.gy[i] * cell + half;
      var vx = homeX - curX, vy = homeY - curY;
      var d2 = vx * vx + vy * vy;
      var tx = 0, ty = 0, ev = 0;

      /* Only particles inside the reach do any trig. */
      if (d2 < reach2) {
        var d = Math.sqrt(d2) || 0.0001;
        var env = 1 - d / reach;
        ev = env * env;
        var phase = field.seed[i] * 6.283;
        var turb = calm ? 0 : ev * driftK;
        tx = (vx / d) * ev * pushK
           + turb * Math.sin(time * 0.9 + (field.gx[i] / field.cols) * 28 + phase)
           + turb * 0.5 * Math.sin(time * 1.9 + phase * 1.7);
        ty = (vy / d) * ev * pushK
           + turb * Math.cos(time * 0.8 + (field.gy[i] / field.rows) * 6.4 + phase)
           + turb * 0.5 * Math.cos(time * 1.7 + phase * 1.3)
           - ev * liftK;
      }

      var dx = field.dx[i] + (tx - field.dx[i]) * EASE;
      var dy = field.dy[i] + (ty - field.dy[i]) * EASE;
      field.dx[i] = dx; field.dy[i] = dy;
      if (!moving && dx * dx + dy * dy > 0.02) moving = true;

      var sz = base * (1 - ev * THIN);
      ctx.fillRect(homeX + dx - sz * 0.5, homeY + dy - sz * 0.5, sz, sz);
    }
    return moving;
  }

  function loop() {
    frame = requestAnimationFrame(loop);
    if (idle || !W) return;
    if (curX < -9000) { curX = targetX; curY = targetY; }
    else { curX += (targetX - curX) * 0.1; curY += (targetY - curY) * 0.1; }
    idle = !step((performance.now() - start) / 1000) && targetX < -9000;
  }

  host.addEventListener("pointermove", function (e) {
    var box = canvas.getBoundingClientRect();
    if (!box.width) return;
    targetX = (e.clientX - box.left) * (W / box.width);
    targetY = (e.clientY - box.top) * (H / box.height);
    idle = false;
  });
  host.addEventListener("pointerleave", function () {
    targetX = -9999; targetY = -9999; idle = false;
  });

  var img = new Image();
  img.onload = function () {
    field = buildField(img);
    layout();
    addEventListener("resize", layout);
    frame = requestAnimationFrame(loop);
  };
  img.src = IMAGE;
})();
</script>
`;
}

/** Constants shared by the two assemble templates. */
function assembleConstants(s: ExportSettings) {
  return `const GRID_W = ${s.gridW};
const INK = ${JSON.stringify(s.ink)};
const GROUND = ${JSON.stringify(s.ground)};
const INVERT = ${s.invert};

/* Tone: which cells survive the dither and become particles. */
const WEIGHT = ${s.weight};
const GAMMA = ${s.gamma};
const BG_CUT = ${s.bgCut};
const FIG_HI = ${s.figHi};
const FADE = ${s.fade};

/* The arrival. Distances are fractions of the picture's own width. */
const DISTANCE = ${s.distance};
const SWIRL = ${s.swirl};
const TURBULENCE = ${s.turbulence};
const STAGGER = ${s.stagger};
const ORDER = ${s.order};
const DURATION = ${s.duration};
/* Square size within its cell, leaving the pixel gap. */
const FILL = ${s.fill};

/* Colour: each cell keeps the colour of the pixel it came from, instead of
   everything being drawn in one ink. Cells are sorted by palette entry so
   painting sets fillStyle once per colour, not once per cell. */
const COLOUR = ${s.colour};
const LEVELS = 8;

const BAYER = ${BAYER_SRC};`;
}

/** A self-contained React client component. No dependencies beyond React. */
export function toReactAssemble(image: string, s: ExportSettings) {
  return `"use client";

/**
 * Picture assembling from dust — generated by Darwin.
 *
 * The image is dithered to a ${s.gridW}-column grid of ink cells; every cell then
 * starts thrown out from the centre, transparent and small, and spirals home
 * while fading up and growing. Departures are staggered, so the picture
 * resolves out of noise rather than sliding into place.
 *
 * It runs once, when the section first comes into view.
 */

import { useEffect, useRef } from "react";

const IMAGE =
  ${JSON.stringify(image)};

${assembleConstants(s)}

const clamp = (v: number, a = 0, b = 1) => Math.max(a, Math.min(b, v));

const smoothstep = (t: number) => {
  const c = clamp(t);
  return c * c * (3 - 2 * c);
};

const easeOutCubic = (t: number) => 1 - Math.pow(1 - t, 3);

type Assembly = {
  gx: Int16Array; gy: Int16Array;
  sx: Float32Array; sy: Float32Array;
  delay: Float32Array; seed: Float32Array;
  n: number; cols: number; rows: number;
  tone?: Uint16Array; palette?: string[];
};

/* Dither the image, then decide where each cell starts from. */
function buildAssembly(image: HTMLImageElement): Assembly {
  const cols = GRID_W;
  const rows = Math.max(1, Math.round((cols * image.naturalHeight) / image.naturalWidth));

  const grid = document.createElement("canvas");
  grid.width = cols;
  grid.height = rows;
  const g = grid.getContext("2d", { willReadFrequently: true })!;
  g.imageSmoothingEnabled = true;
  g.drawImage(image, 0, 0, cols, rows);
  const data = g.getImageData(0, 0, cols, rows).data;

  const xs: number[] = [];
  const ys: number[] = [];
  const tones: number[] = [];
  /* Packed quantised RGB -> palette index. */
  const index = new Map<number, number>();
  const palette: string[] = [];
  const step = 255 / (LEVELS - 1);
  const span = Math.max(1, rows * FADE);

  for (let y = 0; y < rows; y++) {
    const bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const alpha = data[i + 3] / 255;
      const threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

      if (COLOUR) {
        /* Every cell survives; only the bottom fade thins them, and it does so
           through the same Bayer matrix so the edge dissolves rather than cuts. */
        if (alpha < 0.5 || bottom < threshold) continue;
        const qr = Math.round(Math.round(data[i] / step) * step);
        const qg = Math.round(Math.round(data[i + 1] / step) * step);
        const qb = Math.round(Math.round(data[i + 2] / step) * step);
        const packed = (qr << 16) | (qg << 8) | qb;
        let tone = index.get(packed);
        if (tone === undefined) {
          tone = palette.length;
          index.set(packed, tone);
          palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
        }
        xs.push(x);
        ys.push(y);
        tones.push(tone);
        continue;
      }

      let l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      l = l * alpha + 255 * (1 - alpha);
      if (INVERT) l = 255 - l;
      if (l < BG_CUT) continue;

      const value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
      if ((1 - value) * WEIGHT * bottom > threshold) {
        tones.push(0);
        xs.push(x);
        ys.push(y);
      }
    }
  }

  /* Sort by palette entry so painting sets fillStyle once per colour instead
     of once per cell. Squares do not overlap at rest, so reordering is
     invisible. */
  if (COLOUR) {
    const order = xs.map((_, i) => i).sort((a, b) => tones[a] - tones[b]);
    const ox = order.map((i) => xs[i]);
    const oy = order.map((i) => ys[i]);
    const ot = order.map((i) => tones[i]);
    for (let k = 0; k < order.length; k++) {
      xs[k] = ox[k];
      ys[k] = oy[k];
      tones[k] = ot[k];
    }
  }

  const n = xs.length;
  const sx = new Float32Array(n);
  const sy = new Float32Array(n);
  const delay = new Float32Array(n);
  const seed = new Float32Array(n);
  const midX = cols / 2;
  const midY = rows / 2;
  const maxR = Math.hypot(midX, midY) || 1;

  for (let i = 0; i < n; i++) {
    /* Push out along the cell's own line from the centre, so the cloud keeps
       the picture's silhouette instead of collapsing to a disc. */
    const vx = xs[i] - midX;
    const vy = ys[i] - midY;
    const r = Math.hypot(vx, vy) || 0.0001;
    const angle = Math.atan2(vy, vx) + (Math.random() - 0.5) * 1.4;
    const dist = DISTANCE * (0.35 + Math.random() * 0.9);
    sx[i] = Math.cos(angle) * dist;
    sy[i] = Math.sin(angle) * dist;
    seed[i] = Math.random();
    delay[i] = (Math.random() * (1 - ORDER) + (r / maxR) * ORDER) * STAGGER;
  }

  return {
    gx: Int16Array.from(xs), gy: Int16Array.from(ys),
    sx, sy, delay, seed, n, cols, rows,
    tone: COLOUR ? Uint16Array.from(tones) : undefined,
    palette: COLOUR ? palette : undefined,
  };
}

export default function PixelAssemble() {
  const hostRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const host = hostRef.current;
    const canvas = canvasRef.current;
    if (!host || !canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let a: Assembly | null = null;
    let W = 0, H = 0, cell = 1, originX = 0, originY = 0;
    let frame = 0, startedAt = 0, done = false;

    /* Reduced motion: hand over the finished picture rather than flying it in. */
    const calm = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    function layout() {
      if (!a || !host || !canvas || !ctx) return;
      const box = host.getBoundingClientRect();
      if (!box.width || !box.height) return;
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      W = Math.round(box.width * dpr);
      H = Math.round(box.height * dpr);
      canvas.width = W;
      canvas.height = H;
      canvas.style.width = box.width + "px";
      canvas.style.height = box.height + "px";
      /* Leave room around the picture for the dust to arrive from. */
      cell = Math.min((W * 0.62) / a.cols, (H * 0.62) / a.rows);
      originX = (W - a.cols * cell) / 2;
      originY = (H - a.rows * cell) / 2;
      done = false;
    }

    function paint(progress: number, time: number) {
      if (!a || !ctx) return;
      const span = a.cols * cell;
      const base = cell * FILL;
      const half = cell * 0.5;
      /* Departures are staggered but everything still lands together at 1. */
      const window_ = Math.max(0.0001, 1 - STAGGER);
      const turb = TURBULENCE * span;

      ctx.clearRect(0, 0, W, H);
      const tone = a.tone;
      const palette = a.palette;
      /* Cells are sorted by palette entry, so this only changes on a boundary. */
      let last = -1;
      if (!tone || !palette) ctx.fillStyle = INK;

      if (calm || progress >= 1) {
        for (let i = 0; i < a.n; i++) {
          if (tone && palette && tone[i] !== last) {
            last = tone[i];
            ctx.fillStyle = palette[last];
          }
          ctx.fillRect(
            originX + a.gx[i] * cell + half - base * 0.5,
            originY + a.gy[i] * cell + half - base * 0.5,
            base, base
          );
        }
        return;
      }

      for (let i = 0; i < a.n; i++) {
        const local = clamp((progress - a.delay[i]) / window_);
        if (local <= 0) continue;

        const e = easeOutCubic(local);
        const away = 1 - e;
        /* Rotate the start offset by an angle that unwinds as it lands, so the
           path curves in instead of running straight down its own radius. */
        const ang = SWIRL * away;
        const ca = Math.cos(ang), sa = Math.sin(ang);
        const ox = (a.sx[i] * ca - a.sy[i] * sa) * span * away;
        const oy = (a.sx[i] * sa + a.sy[i] * ca) * span * away;

        const phase = a.seed[i] * 6.283;
        const wob = turb * away;
        const jx = wob * Math.sin(time * 1.7 + phase * 2.3);
        const jy = wob * Math.cos(time * 1.4 + phase * 1.9);

        if (tone && palette && tone[i] !== last) {
          last = tone[i];
          ctx.fillStyle = palette[last];
        }
        ctx.globalAlpha = local < 1 ? local : 1;
        const s = base * (0.55 + 0.45 * e);
        ctx.fillRect(
          originX + a.gx[i] * cell + half + ox + jx - s * 0.5,
          originY + a.gy[i] * cell + half + oy + jy - s * 0.5,
          s, s
        );
      }
      ctx.globalAlpha = 1;
    }

    function loop() {
      frame = requestAnimationFrame(loop);
      if (!W || !startedAt || done) return;
      const elapsed = (performance.now() - startedAt) / 1000;
      const progress = Math.min(1, elapsed / DURATION);
      paint(progress, elapsed);
      /* Nothing left to animate once it has landed. */
      if (progress >= 1) done = true;
    }

    const io = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && !startedAt) startedAt = performance.now();
      },
      { threshold: 0.25 }
    );
    const ro = new ResizeObserver(layout);

    const img = new Image();
    img.onload = () => {
      a = buildAssembly(img);
      layout();
      paint(0, 0);
      ro.observe(host);
      io.observe(host);
      frame = requestAnimationFrame(loop);
    };
    img.src = IMAGE;

    return () => {
      if (frame) cancelAnimationFrame(frame);
      ro.disconnect();
      io.disconnect();
    };
  }, []);

  return (
    <div
      ref={hostRef}
      style={{ position: "relative", width: "100%", height: "80vh", background: GROUND }}
    >
      <canvas ref={canvasRef} aria-hidden style={{ display: "block" }} />
    </div>
  );
}
`;
}

/** A single self-contained block for a page that is not running React. */
export function toHtmlAssemble(image: string, s: ExportSettings) {
  return `<!-- Picture assembling from dust — generated by Darwin.
     Paste anywhere in your page. No dependencies, no build step. -->
<div class="pa-host"><canvas class="pa-canvas" aria-hidden="true"></canvas></div>

<style>
  .pa-host { position: relative; width: 100%; height: 80vh; background: ${s.ground}; }
  .pa-canvas { display: block; }
</style>

<script>
(function () {
  var IMAGE =
    ${JSON.stringify(image)};

  ${assembleConstants(s).split("\n").join("\n  ")}

  var host = document.currentScript.parentNode.querySelector(".pa-host")
          || document.querySelector(".pa-host");
  var canvas = host.querySelector(".pa-canvas");
  var ctx = canvas.getContext("2d");

  var a = null, W = 0, H = 0, cell = 1, originX = 0, originY = 0;
  var frame = 0, startedAt = 0, done = false;
  /* Reduced motion: hand over the finished picture rather than flying it in. */
  var calm = matchMedia("(prefers-reduced-motion: reduce)").matches;

  function clamp(v, lo, hi) {
    lo = lo === undefined ? 0 : lo; hi = hi === undefined ? 1 : hi;
    return Math.max(lo, Math.min(hi, v));
  }
  function smoothstep(t) { var c = clamp(t); return c * c * (3 - 2 * c); }
  function easeOutCubic(t) { return 1 - Math.pow(1 - t, 3); }

  function buildAssembly(image) {
    var cols = GRID_W;
    var rows = Math.max(1, Math.round(cols * image.naturalHeight / image.naturalWidth));

    var grid = document.createElement("canvas");
    grid.width = cols; grid.height = rows;
    var g = grid.getContext("2d", { willReadFrequently: true });
    g.imageSmoothingEnabled = true;
    g.drawImage(image, 0, 0, cols, rows);
    var data = g.getImageData(0, 0, cols, rows).data;

    var xs = [], ys = [], x, y;
    var tones = [];
    /* Packed quantised RGB -> palette index. */
    var index = {}, palette = [], step = 255 / (LEVELS - 1);
    var span = Math.max(1, rows * FADE);
    for (y = 0; y < rows; y++) {
      var bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
      for (x = 0; x < cols; x++) {
        var i = (y * cols + x) * 4;
        var alpha = data[i + 3] / 255;
        var threshold = (BAYER[y & 7][x & 7] + 0.5) / 64;

        if (COLOUR) {
          /* Every cell survives; only the bottom fade thins them, through the
             same Bayer matrix so the edge dissolves rather than cuts. */
          if (alpha < 0.5 || bottom < threshold) continue;
          var qr = Math.round(Math.round(data[i] / step) * step);
          var qg = Math.round(Math.round(data[i + 1] / step) * step);
          var qb = Math.round(Math.round(data[i + 2] / step) * step);
          var packed = (qr << 16) | (qg << 8) | qb;
          var tone = index[packed];
          if (tone === undefined) {
            tone = palette.length;
            index[packed] = tone;
            palette.push("rgb(" + qr + "," + qg + "," + qb + ")");
          }
          xs.push(x); ys.push(y); tones.push(tone);
          continue;
        }

        var l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
        l = l * alpha + 255 * (1 - alpha);
        if (INVERT) l = 255 - l;
        if (l < BG_CUT) continue;
        var value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
        if ((1 - value) * WEIGHT * bottom > threshold) {
          tones.push(0);
          xs.push(x); ys.push(y);
        }
      }
    }

    /* Sort by palette entry so painting sets fillStyle once per colour instead
       of once per cell. Squares do not overlap at rest, so reordering is
       invisible. */
    if (COLOUR) {
      var order = xs.map(function (_, i) { return i; })
                    .sort(function (a, b) { return tones[a] - tones[b]; });
      var ox = order.map(function (i) { return xs[i]; });
      var oy = order.map(function (i) { return ys[i]; });
      var ot = order.map(function (i) { return tones[i]; });
      for (var q = 0; q < order.length; q++) {
        xs[q] = ox[q]; ys[q] = oy[q]; tones[q] = ot[q];
      }
    }

    var n = xs.length;
    var sx = new Float32Array(n), sy = new Float32Array(n);
    var delay = new Float32Array(n), seed = new Float32Array(n);
    var midX = cols / 2, midY = rows / 2;
    var maxR = Math.hypot(midX, midY) || 1;

    for (var k = 0; k < n; k++) {
      /* Push out along the cell's own line from the centre, so the cloud keeps
         the picture's silhouette instead of collapsing to a disc. */
      var vx = xs[k] - midX, vy = ys[k] - midY;
      var r = Math.hypot(vx, vy) || 0.0001;
      var angle = Math.atan2(vy, vx) + (Math.random() - 0.5) * 1.4;
      var dist = DISTANCE * (0.35 + Math.random() * 0.9);
      sx[k] = Math.cos(angle) * dist;
      sy[k] = Math.sin(angle) * dist;
      seed[k] = Math.random();
      delay[k] = (Math.random() * (1 - ORDER) + (r / maxR) * ORDER) * STAGGER;
    }

    return {
      gx: Int16Array.from(xs), gy: Int16Array.from(ys),
      sx: sx, sy: sy, delay: delay, seed: seed,
      n: n, cols: cols, rows: rows,
      tone: COLOUR ? Uint16Array.from(tones) : undefined,
      palette: COLOUR ? palette : undefined
    };
  }

  function layout() {
    if (!a) return;
    var box = host.getBoundingClientRect();
    if (!box.width || !box.height) return;
    var dpr = Math.min(devicePixelRatio || 1, 2);
    W = Math.round(box.width * dpr); H = Math.round(box.height * dpr);
    canvas.width = W; canvas.height = H;
    canvas.style.width = box.width + "px";
    canvas.style.height = box.height + "px";
    /* Leave room around the picture for the dust to arrive from. */
    cell = Math.min(W * 0.62 / a.cols, H * 0.62 / a.rows);
    originX = (W - a.cols * cell) / 2;
    originY = (H - a.rows * cell) / 2;
    done = false;
  }

  function paint(progress, time) {
    var span = a.cols * cell, base = cell * FILL, half = cell * 0.5;
    /* Departures are staggered but everything still lands together at 1. */
    var win = Math.max(0.0001, 1 - STAGGER), turb = TURBULENCE * span, i;

    ctx.clearRect(0, 0, W, H);
    var tone = a.tone, palette = a.palette;
    /* Cells are sorted by palette entry, so this only changes on a boundary. */
    var last = -1;
    if (!tone || !palette) ctx.fillStyle = INK;

    if (calm || progress >= 1) {
      for (i = 0; i < a.n; i++) {
        if (tone && palette && tone[i] !== last) {
          last = tone[i]; ctx.fillStyle = palette[last];
        }
        ctx.fillRect(
          originX + a.gx[i] * cell + half - base * 0.5,
          originY + a.gy[i] * cell + half - base * 0.5, base, base);
      }
      return;
    }

    for (i = 0; i < a.n; i++) {
      var local = clamp((progress - a.delay[i]) / win);
      if (local <= 0) continue;
      var e = easeOutCubic(local), away = 1 - e;
      /* Rotate the start offset by an angle that unwinds as it lands. */
      var ang = SWIRL * away, ca = Math.cos(ang), sa = Math.sin(ang);
      var ox = (a.sx[i] * ca - a.sy[i] * sa) * span * away;
      var oy = (a.sx[i] * sa + a.sy[i] * ca) * span * away;
      var phase = a.seed[i] * 6.283, wob = turb * away;
      var jx = wob * Math.sin(time * 1.7 + phase * 2.3);
      var jy = wob * Math.cos(time * 1.4 + phase * 1.9);

      if (tone && palette && tone[i] !== last) {
        last = tone[i]; ctx.fillStyle = palette[last];
      }
      ctx.globalAlpha = local < 1 ? local : 1;
      var sz = base * (0.55 + 0.45 * e);
      ctx.fillRect(
        originX + a.gx[i] * cell + half + ox + jx - sz * 0.5,
        originY + a.gy[i] * cell + half + oy + jy - sz * 0.5, sz, sz);
    }
    ctx.globalAlpha = 1;
  }

  function loop() {
    frame = requestAnimationFrame(loop);
    if (!W || !startedAt || done) return;
    var elapsed = (performance.now() - startedAt) / 1000;
    var progress = Math.min(1, elapsed / DURATION);
    paint(progress, elapsed);
    /* Nothing left to animate once it has landed. */
    if (progress >= 1) done = true;
  }

  var img = new Image();
  img.onload = function () {
    a = buildAssembly(img);
    layout();
    paint(0, 0);
    addEventListener("resize", layout);
    new IntersectionObserver(function (entries) {
      if (entries[0].isIntersecting && !startedAt) startedAt = performance.now();
    }, { threshold: 0.25 }).observe(host);
    frame = requestAnimationFrame(loop);
  };
  img.src = IMAGE;
})();
</script>
`;
}

export function formatBytes(n: number) {
  if (n < 1024) return n + " B";
  if (n < 1048576) return (n / 1024).toFixed(0) + " KB";
  return (n / 1048576).toFixed(2) + " MB";
}
