import type { DitherOptions } from "@/lib/dither";

/**
 * Code generation for the studio.
 *
 * What comes out has to survive leaving this repo, so it carries no imports
 * from here, no Motion, and no Tailwind — just React (or nothing at all, for
 * the HTML build) and a canvas. The image travels with it as a data URI, and
 * the develop lag is a hand-rolled lerp rather than a spring, so there is
 * nothing to install.
 */

export type ExportSettings = DitherOptions & {
  ink: string;
  ground: string;
  round: boolean;
  /** Scroll the develop takes, as a multiple of the viewport height. */
  runway: number;
  /** Develop lag per frame: 0 snaps to the scrollbar, 1 never catches up. */
  ease: number;
};

const BAYER_SRC = `[
  [0, 32, 8, 40, 2, 34, 10, 42],
  [48, 16, 56, 24, 50, 18, 58, 26],
  [12, 44, 4, 36, 14, 46, 6, 38],
  [60, 28, 52, 20, 62, 30, 54, 22],
  [3, 35, 11, 43, 1, 33, 9, 41],
  [51, 19, 59, 27, 49, 17, 57, 25],
  [15, 47, 7, 39, 13, 45, 5, 37],
  [63, 31, 55, 23, 61, 29, 53, 21],
]`;

function constants(s: ExportSettings) {
  return `const GRID_W = ${s.gridW};
const INK = ${JSON.stringify(s.ink)};
const GROUND = ${JSON.stringify(s.ground)};
const ROUND = ${s.round};
const INVERT = ${s.invert};

/* Tone: how luminance becomes ink density. */
const WEIGHT = ${s.weight};
const GAMMA = ${s.gamma};
const BG_CUT = ${s.bgCut};
const FIG_HI = ${s.figHi};
/* Fraction of the height over which the print dissolves at its bottom edge. */
const FADE = ${s.fade};

/* Develop: per-cell thresholds, and how wide each cell's fade-in is. */
const SPREAD = ${s.spread};
const CELL_FADE = 0.06;
/* Scroll the develop takes, as a multiple of the viewport height. */
const RUNWAY = ${s.runway};
/* Develop lag per frame: 0 snaps to the scrollbar, 1 never catches up. */
const EASE = ${s.ease};

const BAYER = ${BAYER_SRC};`;
}

/** A self-contained React client component. No dependencies beyond React. */
export function toReact(image: string, s: ExportSettings) {
  return `"use client";

/**
 * Scroll-developed dither — generated by Darwin.
 *
 * The image is sampled to a ${s.gridW}-column grid and thresholded through an 8x8
 * Bayer matrix, so tone is carried by how many cells survive in a neighbourhood
 * rather than by any grey. Each surviving cell gets its own threshold, and
 * scroll progress sweeps past them, so the picture comes up in grain like a
 * darkroom print instead of wiping or fading in.
 *
 * Drop it anywhere. The section is ${s.runway} viewports tall and pins its own stage,
 * so it needs no wrapper and no scroll library.
 */

import { useEffect, useRef } from "react";

const IMAGE =
  ${JSON.stringify(image)};

${constants(s)}

type Cells = { x: Int16Array; y: Int16Array; t: Float32Array; n: number; cols: number; rows: number };

const clamp = (v: number, a = 0, b = 1) => Math.max(a, Math.min(b, v));

const smoothstep = (t: number) => {
  const c = clamp(t);
  return c * c * (3 - 2 * c);
};

/* Deterministic, so the picture always develops in the same order. */
function hash(x: number, y: number) {
  const h = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
  return h - Math.floor(h);
}

function buildCells(image: HTMLImageElement): Cells {
  const cols = GRID_W;
  const rows = Math.max(1, Math.round((cols * image.naturalHeight) / image.naturalWidth));

  const grid = document.createElement("canvas");
  grid.width = cols;
  grid.height = rows;
  const gctx = grid.getContext("2d", { willReadFrequently: true })!;
  gctx.imageSmoothingEnabled = true;
  gctx.drawImage(image, 0, 0, cols, rows);
  const data = gctx.getImageData(0, 0, cols, rows).data;

  const xs: number[] = [];
  const ys: number[] = [];
  const ts: number[] = [];
  const span = Math.max(1, rows * FADE);

  for (let y = 0; y < rows; y++) {
    const bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
    for (let x = 0; x < cols; x++) {
      const i = (y * cols + x) * 4;
      const alpha = data[i + 3] / 255;
      let l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
      l = l * alpha + 255 * (1 - alpha);
      if (INVERT) l = 255 - l;
      if (l < BG_CUT) continue;

      const value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
      if ((1 - value) * WEIGHT * bottom > (BAYER[y & 7][x & 7] + 0.5) / 64) {
        xs.push(x);
        ys.push(y);
        ts.push(clamp(hash(x, y) * SPREAD));
      }
    }
  }

  return {
    x: Int16Array.from(xs),
    y: Int16Array.from(ys),
    t: Float32Array.from(ts),
    n: xs.length,
    cols,
    rows,
  };
}

export default function ScrollDither() {
  const sectionRef = useRef<HTMLElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const section = sectionRef.current;
    const canvas = canvasRef.current;
    if (!section || !canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let cells: Cells | null = null;
    let cell = 1;
    let current = 0;
    let frame = 0;
    /* Reduced motion keeps the scroll — that is the user's own gesture — and
       drops only the lag, so nothing keeps moving after they stop. */
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    function layout() {
      if (!cells || !ctx || !canvas || !section) return;
      const box = section.getBoundingClientRect();
      const stage = Math.min(window.innerHeight, box.height);
      cell = Math.min((box.width * 0.8) / cells.cols, (stage * 0.88) / cells.rows);

      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      canvas.style.width = cells.cols * cell + "px";
      canvas.style.height = cells.rows * cell + "px";
      canvas.width = Math.round(cells.cols * cell * dpr);
      canvas.height = Math.round(cells.rows * cell * dpr);
      /* Assigning width/height clears the transform, so set it after. */
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      paint(current);
    }

    function progress() {
      if (!section) return 0;
      const r = section.getBoundingClientRect();
      const total = section.offsetHeight - window.innerHeight;
      return total > 0 ? clamp(-r.top / total) : 0;
    }

    function paint(p: number) {
      if (!cells || !ctx) return;
      ctx.clearRect(0, 0, cells.cols * cell, cells.rows * cell);
      ctx.fillStyle = INK;
      const r = cell / 2;
      const settled = p > 0.999;

      for (let i = 0; i < cells.n; i++) {
        if (!settled) {
          const a = (p - cells.t[i]) / CELL_FADE;
          if (a <= 0) continue;
          ctx.globalAlpha = a < 1 ? a : 1;
        }
        const px = cells.x[i] * cell;
        const py = cells.y[i] * cell;
        if (ROUND) {
          ctx.beginPath();
          ctx.arc(px + r, py + r, r, 0, 6.2832);
          ctx.fill();
        } else {
          ctx.fillRect(px, py, cell, cell);
        }
      }
      ctx.globalAlpha = 1;
    }

    function loop() {
      const target = progress();
      current = reduce ? target : current + (target - current) * EASE;
      paint(current);
      frame = requestAnimationFrame(loop);
    }

    /* Only run while the section is on screen. */
    const io = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          if (!frame) frame = requestAnimationFrame(loop);
        } else if (frame) {
          cancelAnimationFrame(frame);
          frame = 0;
        }
      },
      { rootMargin: "200px" }
    );

    const ro = new ResizeObserver(layout);
    const img = new Image();
    img.onload = () => {
      cells = buildCells(img);
      layout();
      ro.observe(section);
      io.observe(section);
    };
    img.src = IMAGE;

    return () => {
      if (frame) cancelAnimationFrame(frame);
      ro.disconnect();
      io.disconnect();
    };
  }, []);

  return (
    <section
      ref={sectionRef}
      style={{ position: "relative", height: \`\${RUNWAY * 100}vh\`, background: GROUND }}
    >
      <div
        style={{
          position: "sticky",
          top: 0,
          height: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          overflow: "hidden",
        }}
      >
        <canvas ref={canvasRef} aria-hidden style={{ display: "block" }} />
      </div>
    </section>
  );
}
`;
}

/** A single self-contained block for a page that is not running React. */
export function toHtml(image: string, s: ExportSettings) {
  return `<!-- Scroll-developed dither — generated by Darwin.
     Paste anywhere in your page. No dependencies, no build step. -->
<section class="sd-scene">
  <div class="sd-stage"><canvas class="sd-canvas" aria-hidden="true"></canvas></div>
</section>

<style>
  .sd-scene { position: relative; height: ${s.runway * 100}vh; background: ${s.ground}; }
  .sd-stage { position: sticky; top: 0; height: 100vh; display: flex;
              align-items: center; justify-content: center; overflow: hidden; }
  .sd-canvas { display: block; }
</style>

<script>
(function () {
  var IMAGE =
    ${JSON.stringify(image)};

  ${constants(s).split("\n").join("\n  ")}

  var scene = document.currentScript.parentNode.querySelector(".sd-scene")
           || document.querySelector(".sd-scene");
  var canvas = scene.querySelector(".sd-canvas");
  var ctx = canvas.getContext("2d");

  var cells = null, cell = 1, current = 0, frame = 0;
  /* Reduced motion keeps the scroll — that is the user's own gesture — and
     drops only the lag, so nothing keeps moving after they stop. */
  var reduce = matchMedia("(prefers-reduced-motion: reduce)").matches;

  function clamp(v, a, b) {
    a = a === undefined ? 0 : a; b = b === undefined ? 1 : b;
    return Math.max(a, Math.min(b, v));
  }
  function smoothstep(t) { var c = clamp(t); return c * c * (3 - 2 * c); }
  function hash(x, y) {
    var h = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
    return h - Math.floor(h);
  }

  function buildCells(image) {
    var cols = GRID_W;
    var rows = Math.max(1, Math.round(cols * image.naturalHeight / image.naturalWidth));

    var grid = document.createElement("canvas");
    grid.width = cols; grid.height = rows;
    var g = grid.getContext("2d", { willReadFrequently: true });
    g.imageSmoothingEnabled = true;
    g.drawImage(image, 0, 0, cols, rows);
    var data = g.getImageData(0, 0, cols, rows).data;

    var xs = [], ys = [], ts = [];
    var span = Math.max(1, rows * FADE);

    for (var y = 0; y < rows; y++) {
      var bottom = FADE > 0 ? smoothstep((rows - y) / span) : 1;
      for (var x = 0; x < cols; x++) {
        var i = (y * cols + x) * 4;
        var alpha = data[i + 3] / 255;
        var l = 0.299 * data[i] + 0.587 * data[i + 1] + 0.114 * data[i + 2];
        l = l * alpha + 255 * (1 - alpha);
        if (INVERT) l = 255 - l;
        if (l < BG_CUT) continue;

        var value = Math.pow(clamp((l - BG_CUT) / (FIG_HI - BG_CUT)), GAMMA);
        if ((1 - value) * WEIGHT * bottom > (BAYER[y & 7][x & 7] + 0.5) / 64) {
          xs.push(x); ys.push(y); ts.push(clamp(hash(x, y) * SPREAD));
        }
      }
    }

    return {
      x: Int16Array.from(xs), y: Int16Array.from(ys), t: Float32Array.from(ts),
      n: xs.length, cols: cols, rows: rows
    };
  }

  function layout() {
    if (!cells) return;
    var box = scene.getBoundingClientRect();
    var stage = Math.min(innerHeight, box.height);
    cell = Math.min(box.width * 0.8 / cells.cols, stage * 0.88 / cells.rows);

    var dpr = Math.min(devicePixelRatio || 1, 2);
    canvas.style.width = cells.cols * cell + "px";
    canvas.style.height = cells.rows * cell + "px";
    canvas.width = Math.round(cells.cols * cell * dpr);
    canvas.height = Math.round(cells.rows * cell * dpr);
    /* Assigning width/height clears the transform, so set it after. */
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    paint(current);
  }

  function progress() {
    var r = scene.getBoundingClientRect();
    var total = scene.offsetHeight - innerHeight;
    return total > 0 ? clamp(-r.top / total) : 0;
  }

  function paint(p) {
    if (!cells) return;
    ctx.clearRect(0, 0, cells.cols * cell, cells.rows * cell);
    ctx.fillStyle = INK;
    var r = cell / 2, settled = p > 0.999, i, a, px, py;

    for (i = 0; i < cells.n; i++) {
      if (!settled) {
        a = (p - cells.t[i]) / CELL_FADE;
        if (a <= 0) continue;
        ctx.globalAlpha = a < 1 ? a : 1;
      }
      px = cells.x[i] * cell; py = cells.y[i] * cell;
      if (ROUND) { ctx.beginPath(); ctx.arc(px + r, py + r, r, 0, 6.2832); ctx.fill(); }
      else ctx.fillRect(px, py, cell, cell);
    }
    ctx.globalAlpha = 1;
  }

  function loop() {
    var target = progress();
    current = reduce ? target : current + (target - current) * EASE;
    paint(current);
    frame = requestAnimationFrame(loop);
  }

  var img = new Image();
  img.onload = function () {
    cells = buildCells(img);
    layout();
    addEventListener("resize", layout);
    /* Only run while the section is on screen. */
    new IntersectionObserver(function (entries) {
      if (entries[0].isIntersecting) { if (!frame) frame = requestAnimationFrame(loop); }
      else if (frame) { cancelAnimationFrame(frame); frame = 0; }
    }, { rootMargin: "200px" }).observe(scene);
  };
  img.src = IMAGE;
})();
</script>
`;
}

export function formatBytes(n: number) {
  if (n < 1024) return n + " B";
  if (n < 1048576) return (n / 1024).toFixed(0) + " KB";
  return (n / 1048576).toFixed(2) + " MB";
}
